apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
bases:
  - ../../base
patches:
  - path: onprem-install-logging.yaml 
    target:
      kind: Policy
  - path: onprem-placement-rule.yaml
    target:
      kind: PlacementRule

  
