apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: onprem-install-logging-placement
  namespace: policies
spec:
  clusterConditions: []
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - DUMMY 
